---
- hosts: all
  become: true
  
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
        
    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages
    
    - name: Check whether a package called git is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['git'] | length }} versions of git are installed!"
      when: "'git' in ansible_facts.packages"

    - name: Install package if not present 
      yum:
        name: git
        state: present
      when: "'git' not in ansible_facts.packages"