---
- hosts: all
  become: true
  vars_files:
   variable-file.yaml
  tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: latest

    - name: copy index.html
      template: 
        src: index.html
        dest: /var/www/html/index.html
      notify: 
      - restart httpd server

  handlers:
    - name: restart httpd server
      service: 
        name: httpd
        state: restarted
        enabled: true
...
