---
- hosts: all
  become: true
  tasks:
    - name: install git on Redhat
      yum: 
        name: git
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install git on ubuntu
      apt: 
        name: git
        state: latest
      when: ansible_os_family == "Debian"

